# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api: new
  api_key: "179741908724938"
  secret_key: "4d1d96dc9b402ca6779f77bc9e88b89a"
  canvas_page_name:
  callback_url: http://test.commonplace.co/account/new
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username: deploy
    public_host: staging.commonplaceusa.com
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

staging:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url: 
  set_asset_host_to_callback_url: true   
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0
